export const MODEL = [{"mark":"Nissan"},
{"mark":"Ferrari"},
{"mark":"Mazda"},
{"mark":"Scion"},
{"mark":"Hummer"},
{"mark":"Chrysler"},
{"mark":"Honda"},
{"mark":"MINI"},
{"mark":"Jeep"},
{"mark":"Hyundai"},
{"mark":"Dodge"},
{"mark":"Porsche"},
{"mark":"Subaru"},
{"mark":"Ford"},
{"mark":"Chevrolet"}]